In [43]:
# Importing required libraries

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score , mean_squared_error

In [45]:
# Loading the dataset

house_data = pd.read_csv("HousePricePrediction.csv")

house_data.head(10)

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
5,5,50,RL,14115,Inside,1Fam,5,1993,1995,VinylSd,0.0,796.0,143000.0
6,6,20,RL,10084,Inside,1Fam,5,2004,2005,VinylSd,0.0,1686.0,307000.0
7,7,60,RL,10382,Corner,1Fam,6,1973,1973,HdBoard,32.0,1107.0,200000.0
8,8,50,RM,6120,Inside,1Fam,5,1931,1950,BrkFace,0.0,952.0,129900.0
9,9,190,RL,7420,Corner,2fmCon,6,1939,1950,MetalSd,0.0,991.0,118000.0

In [48]:
# Understanding the dataset structure

house_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

In [49]:
# Checking missing values

house_data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           4
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        1
BsmtFinSF2         1
TotalBsmtSF        1
SalePrice       1459
dtype: int64

In [7]:
df = house_data.copy()

df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

In [9]:
df["MSZoning"] = df["MSZoning"].fillna(df["MSZoning"].mode()[0])

df["Exterior1st"] = df["Exterior1st"].fillna(df["Exterior1st"].mode()[0])

df["BsmtFinSF2"] = df["BsmtFinSF2"].fillna(df["BsmtFinSF2"].median())

df["TotalBsmtSF"] = df["TotalBsmtSF"].fillna(df["TotalBsmtSF"].median())


df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        0
BsmtFinSF2         0
TotalBsmtSF        0
SalePrice       1459
dtype: int64

In [10]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [11]:
df["MSZoning"].value_counts()

MSZoning
RL         2269
RM          460
FV          139
RH           26
C (all)      25
Name: count, dtype: int64

In [12]:
# One Hot Encoding - MSZoning

df = pd.get_dummies(data= df , columns=["MSZoning"] , drop_first=True , dtype=int)

In [13]:
# One Hot Encoding - LotConfig

df = pd.get_dummies(data= df , columns=["LotConfig"] , drop_first=True , dtype=int)

In [14]:
# One Hot Encoding - BldgType

df = pd.get_dummies(data= df , columns=["BldgType"] , drop_first=True , dtype=int)

In [15]:
# One Hot Encoding - Exterior1st

df = pd.get_dummies(data= df , columns=["Exterior1st"] , drop_first=True , dtype=int)

In [50]:
df.head()

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_FV,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,0,60,8450,5,2003,2003,0.0,856.0,208500.0,0,...,0,0,0,0,0,0,0,1,0,0
1,1,20,9600,8,1976,1976,0.0,1262.0,181500.0,0,...,0,0,0,1,0,0,0,0,0,0
2,2,60,11250,5,2001,2002,0.0,920.0,223500.0,0,...,0,0,0,0,0,0,0,1,0,0
3,3,70,9550,5,1915,1970,0.0,756.0,140000.0,0,...,0,0,0,0,0,0,0,0,1,0
4,4,60,14260,5,2000,2000,0.0,1145.0,250000.0,0,...,0,0,0,0,0,0,0,1,0,0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   2919 non-null   int64
 1   MSSubClass           2919 non-null   int64
 2   LotArea              2919 non-null   int64
 3   OverallCond          2919 non-null   int64
 4   YearBuilt            2919 non-null   int64
 5   YearRemodAdd         2919 non-null   int64
 6   BsmtFinSF2           2919 non-null   float64
 7   TotalBsmtSF          2919 non-null   float64
 8   SalePrice            1460 non-null   float64
 9   MSZoning_FV          2919 non-null   int64
 10  MSZoning_RH          2919 non-null   int64
 11  MSZoning_RL          2919 non-null   int64
 12  MSZoning_RM          2919 non-null   int64
 13  LotConfig_CulDSac    2919 non-null   int64
 14  LotConfig_FR2        2919 non-null   int64
 15  LotConfig_FR3        2919 non-null   int64
 16  LotConfig_Inside     2919 non-null   int64
 17  BldgType_2fmCon      2919 non-null   int64
 18  BldgType_Duplex      2919 non-null   int64
 19  BldgType_Twnhs       2919 non-null   int64
 20  BldgType_TwnhsE      2919 non-null   int64
 21  Exterior1st_AsphShn  2919 non-null   int64
 22  Exterior1st_BrkComm  2919 non-null   int64
 23  Exterior1st_BrkFace  2919 non-null   int64
 24  Exterior1st_CBlock   2919 non-null   int64
 25  Exterior1st_CemntBd  2919 non-null   int64
 26  Exterior1st_HdBoard  2919 non-null   int64
 27  Exterior1st_ImStucc  2919 non-null   int64
 28  Exterior1st_MetalSd  2919 non-null   int64
 29  Exterior1st_Plywood  2919 non-null   int64
 30  Exterior1st_Stone    2919 non-null   int64
 31  Exterior1st_Stucco   2919 non-null   int64
 32  Exterior1st_VinylSd  2919 non-null   int64
 33  Exterior1st_Wd Sdng  2919 non-null   int64
 34  Exterior1st_WdShing  2919 non-null   int64
dtypes: float64(3), int64(32)
memory usage: 798.3 KB

In [18]:
df["SalePrice"].notnull().sum()

np.int64(1460)

In [19]:
train_df = df[df["SalePrice"].notnull()]

In [20]:
train_df

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_FV,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,0,60,8450,5,2003,2003,0.0,856.0,208500.0,0,...,0,0,0,0,0,0,0,1,0,0
1,1,20,9600,8,1976,1976,0.0,1262.0,181500.0,0,...,0,0,0,1,0,0,0,0,0,0
2,2,60,11250,5,2001,2002,0.0,920.0,223500.0,0,...,0,0,0,0,0,0,0,1,0,0
3,3,70,9550,5,1915,1970,0.0,756.0,140000.0,0,...,0,0,0,0,0,0,0,0,1,0
4,4,60,14260,5,2000,2000,0.0,1145.0,250000.0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,60,7917,5,1999,2000,0.0,953.0,175000.0,0,...,0,0,0,0,0,0,0,1,0,0
1456,1456,20,13175,6,1978,1988,163.0,1542.0,210000.0,0,...,0,0,0,0,1,0,0,0,0,0
1457,1457,70,9042,9,1941,2006,0.0,1152.0,266500.0,0,...,1,0,0,0,0,0,0,0,0,0
1458,1458,20,9717,6,1950,1996,1029.0,1078.0,142125.0,0,...,0,0,0,1,0,0,0,0,0,0
1459,1459,20,9937,6,1965,1965,290.0,1256.0,147500.0,0,...,0,1,0,0,0,0,0,0,0,0

In [21]:
train_df = train_df.drop("Id" , axis = 1)

In [51]:
# After Data Cleaning Process

train_df.isnull().sum()

MSSubClass             0
LotArea                0
OverallCond            0
YearBuilt              0
YearRemodAdd           0
BsmtFinSF2             0
TotalBsmtSF            0
SalePrice              0
MSZoning_FV            0
MSZoning_RH            0
MSZoning_RL            0
MSZoning_RM            0
LotConfig_CulDSac      0
LotConfig_FR2          0
LotConfig_FR3          0
LotConfig_Inside       0
BldgType_2fmCon        0
BldgType_Duplex        0
BldgType_Twnhs         0
BldgType_TwnhsE        0
Exterior1st_AsphShn    0
Exterior1st_BrkComm    0
Exterior1st_BrkFace    0
Exterior1st_CBlock     0
Exterior1st_CemntBd    0
Exterior1st_HdBoard    0
Exterior1st_ImStucc    0
Exterior1st_MetalSd    0
Exterior1st_Plywood    0
Exterior1st_Stone      0
Exterior1st_Stucco     0
Exterior1st_VinylSd    0
Exterior1st_Wd Sdng    0
Exterior1st_WdShing    0
dtype: int64

In [52]:
# Splitting data into training and testing sets

X = train_df.drop("SalePrice" , axis=1)

y = train_df["SalePrice"]

In [53]:
# Training the Linear Regression model

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

model = LinearRegression()

model.fit(X_train , y_train)

y_pred = model.predict(X_test)

In [54]:
# Evaluating model performance using MSE, RMSE and R² Score

mse = mean_squared_error(y_test , y_pred)
r2 = r2_score(y_test , y_pred)
rmse = np.sqrt(mse)


print(f"MSE: {mse}")
print(f"r2 Score: {r2}")
print(f"RMSE: {rmse}")

MSE: 2918458029.585501
r2 Score: 0.6195131796544853
RMSE: 54022.754738957

In [55]:
# Adjusted r2

n = X_test.shape[0]
p = X_test.shape[1]

adj_r2 = 1 - ((1-r2) * (n-1) / (n-p-1))
adj_r2

0.5708462607730822